[package]
authors = ["Brandon Edens <brandonedens@gmail.com>",
		"Jorge Aparicio <japaricious@gmail.com>"]
description = "Memory map for STM32L4x6 microcontrollers"
keywords = ["arm", "cortex-m", "stm32", "stm32l4"]
license = "MIT OR Apache-2.0"
name = "stm32l4x6-memory-map"
repository = "https://github.com/brandonedens/stm32l4x6-memory-map"
version = "0.1.2"

[dependencies]
volatile-register = "0.1.2"
